id: P85C3C25C
initial_creation_type: input
source_metadata:
  title: Dīrghāgama, sūtras no. 35-41
  language: bo
  volumes:
    6dd4dde7e86f4f628e998eaf4fc872ec:
      title: Complete text
      base_file: Complete text.txt
      work_id: W95FA7C69
  chapter_to_tile: {}
created_at: '2022-03-02T08:54:17.919778'
last_modified_at: '2022-03-02T08:54:17.919799'
